### ISSUE TITLE
Got "TypeError: 'generator' object is not subscriptable" on my Ubuntu machine

### ISSUE THREAD

**Issue by Michael89** [hyperopt/hyperopt#325]
Hi I'm trining to use your grate lib for tuning hyperparameters for my NN, but for some reason I got this error:

```Traceback (most recent call last):
  File "/home/michael/work/oanda/src/oanda/trend_prediction/find_optimal_model.py", line 124, in <module>
    main()
  File "/home/michael/work/oanda/src/oanda/trend_prediction/find_optimal_model.py", line 116, in main
    trials=trials)
  File "/home/michael/work/oanda/runtime/lib/python3.5/site-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/home/michael/work/oanda/runtime/lib/python3.5/site-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/home/michael/work/oanda/runtime/lib/python3.5/site-packages/hyperopt/fmin.py", line 314, in fmin
    pass_expr_memo_ctrl=pass_expr_memo_ctrl)
  File "/home/michael/work/oanda/runtime/lib/python3.5/site-packages/hyperopt/base.py", line 786, in __init__
    pyll.toposort(self.expr)
  File "/home/michael/work/oanda/runtime/lib/python3.5/site-packages/hyperopt/pyll/base.py", line 715, in toposort
    assert order[-1] == expr
TypeError: 'generator' object is not subscriptable
```

Everything work nice when I tried it on my mac book but when I start it on my desktop (which I build for NN training) I got this error and don't know what to do.

`Python 3.5.2`
`Linux michael-ubuntu 4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:2`

**Comment by Michael89** [comment]
Find a quick fix. I noticed that I have networkx-2.0 version on ubuntu and networkx-1.11 on mac so I just downgrade it on ubuntu and it starts working.

**Comment by lferrerg** [comment]
Thanks @Michael89 for your quick fix! I confirm that networkx-2.0 is the culprit of the error and downgrading to version 1.11 does the trick.

**Comment by charlesreid1** [comment]
Thanks for this. For anyone wondering how to downgrade:

```
$ pip install networkx==1.11
```

**Comment by authman** [comment]
Seems this is still an issue

**Comment by michaelmior** [comment]
This was fixed in #319 but you'll either have to run with the code from the repository or wait for the next release.

**Comment by juharris** [comment]
Do `pip install --upgrade git+git://github.com/hyperopt/hyperopt.git` until a new release has been made.

**Comment by olddaos** [comment]
Hi guys!
Looks like it is still an issue on my Mac ( Darwin Kernel Version 16.6.0: Fri Apr 14 16:13:31 PDT 2017; root:xnu-3789.60.24~4/RELEASE_X86_64 x86_64) with Python 3.6.3

Just did 'pip install --upgrade git+git://github.com/hyperopt/hyperopt.git', downgraded networkx but nothing helps...

Thanks in advance for any clues.

**Comment by michaelmior** [comment]
Don't really see how this would be possible since `order` is explicitly converted to a list. Can you check that `hyperopt/pyll/base.py` in your hyperopt installation matches what's in master?

**Comment by olddaos** [comment]
Excuse please and thank you for prompt reply.

I already restarted iPython notebook and everything is fine.

Cheers,
Alexey

пятница, 15 июня 2018 г. пользователь Michael Mior написал:

**Comment by wernight** [comment]
Wondering what's blocking creating a new release. Having unpinned versions isn't healthy or easy to maintain as general creating a new release is rather easy.

**Comment by maxpumperla** [comment]
I can do a release next week

**Comment by nqnhu1** [comment]
Have anyone gotten to solve it yet please? I got a similar error  'int' object is not subscriptable. I'm having a hard time trying to figure it out

**Comment by michaelmior** [comment]
@nqnhu1 Try using the version of hyperopt on the master branch.
